name: satellite-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core scientific computing
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - pillow=10.0.1
  
  # Geospatial core libraries
  - gdal=3.7.2
  - geos=3.11.2
  - proj=9.2.1
  - libspatialindex=1.9.3
  
  # Python geospatial packages
  - rasterio=1.3.8
  - geopandas=0.13.2
  - shapely=2.0.1
  - fiona=1.9.4
  - pyproj=3.6.0
  - rtree=1.0.1
  
  # Additional utilities
  - pip=23.2.1
  - setuptools=68.0.0
  - wheel=0.41.2